DROP TABLE IF EXISTS shots;

CREATE TABLE shots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    cost INTEGER,
    budget INTEGER
);
